image:
  repository: tccr.io/truecharts/uptime-kuma
  pullPolicy: IfNotPresent
  tag: 1.21.2@sha256:053a4fde5436c2cebe2136edf6e5c786e43c5410bca423f0f6920dc7ccee3f68
security:
  PUID: 0
service:
  main:
    ports:
      main:
        port: 3001
persistence:
  config:
    enabled: true
    mountPath: "/app/data"
portal:
  open:
    enabled: true
metrics:
  main:
    enabled: true
    type: "servicemonitor"
    endpoints:
      - port: metrics
        path: /metrics
    prometheusRule:
      enabled: false

securityContext:
  container:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            UPTIME_KUMA_PORT: "{{ .Values.service.main.ports.main.port }}"
