apiVersion: v2
appVersion: "2023.02.2"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 11.1.2
deprecated: false
description: DNS and Ad-filtering for your network
home: https://truecharts.org/charts/stable/pihole
icon: https://truecharts.org/img/hotlink-ok/chart-icons/pihole.png
keywords:
  - DNS
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: pihole
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/pihole
  - https://hub.docker.com/r/pihole/pihole
  - https://pi-hole.net/
  - https://github.com/pi-hole
  - https://github.com/pi-hole/docker-pi-hole
type: application
version: 8.0.19
annotations:
  truecharts.org/catagories: |
    - networking
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
