image:
  repository: tccr.io/truecharts/pihole
  pullPolicy: IfNotPresent
  tag: 2023.02.2@sha256:e49fd7cf10284ce200bf86fd5a61f81295014d01c079766a77661dba1b36489e

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  allowPrivilegeEscalation: true

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

envFrom:
  - configMapRef:
      name: pihole-env

service:
  main:
    ports:
      main:
        port: 9089
        targetPort: 80
  dns-tcp:
    enabled: true
    ports:
      dns-tcp:
        enabled: true
        port: 53
        targetPort: 53
  dns:
    enabled: true
    ports:
      dns:
        enabled: true
        protocol: UDP
        port: 53
        targetPort: 53

pihole:
  WEBPASSWORD: "somepassword"
  DNS1: "9.9.9.9"
  DNS2: "149.112.112.112"

persistence:
  config:
    enabled: true
    mountPath: "/etc/pihole"
  dnsmasq:
    enabled: true
    mountPath: "/etc/dnsmasq.d"

portal:
  enabled: true
